name: klio dependency compatibility checks

on:
  schedule:
    # Run once daily
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
      - develop
      - release-*
    paths-ignore:
      - 'docs/**'
      - 'devtools/**'
      - 'examples/**'
      - '**.rst'
  pull_request:
    branches:
      - master
      - develop
      - release-*
    paths-ignore:
      - 'docs/**'
      - 'devtools/**'
      - 'examples/**'
      - '**.rst'

jobs:
  core_cli_checks:
    name: "klio: verify no dependency conflicts between core/cli"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.7"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools
      - name: "Install klio_core"
        run: |
          python -m pip install -e core
          python -m pip check
      - name: "Install klio_cli"
        run: |
          python -m pip install -e cli
          python -m pip check
  core_lib_exec_checks:
    name: "klio: verify no dependency conflicts between core/lib/exec"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.7"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools
      - name: "Install klio_core"
        run: |
          python -m pip install -e core
          python -m pip check
      - name: "Install klio_lib"
        run: |
          python -m pip install -e lib
          python -m pip check
      - name: "Install klio_exec"
        run: |
          python -m pip install -e exec
          python -m pip check
