name: klio integration tests

on:
  push:
    branches:
      - master
      - develop
      - release-*
    paths-ignore:
      - 'docs/**'
      - 'devtools/**'
      - 'examples/**'
      - '**.rst'
  pull_request:
    branches:
      - master
      - develop
      - release-*
    paths-ignore:
      - 'docs/**'
      - 'devtools/**'
      - 'examples/**'
      - '**.rst'

defaults:
  run:
    working-directory: integration

jobs:
  tests:
    name: "Integration Tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        test-dir:
          - "read-file-write-file"
          - "multi-event-input-batch"
          - "read-file"
          - "batch-modular-default"
          - "audio-spectrograms"
          - "read-bq-write-bq"
      # do not cancel other jobs in matrix if one fails
      fail-fast: false
    steps:
      - uses: "actions/checkout@v2"
      - name: Decrypt GCP credentials
        working-directory: .github/scripts
        run: ./decrypt_it_creds.sh
        env:
          IT_GCP_CREDS_KEY: ${{ secrets.IT_GCP_CREDS_KEY }}
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.7"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: "Run Integration Test ${{ matrix.test-dir }} with python 3.7"
        run: "KLIO_TEST_DIR=${{ matrix.test-dir }} python -m tox -c tox.ini"
      - name: "Assert Apache License Headers & Copyright"
        run: |
          pip install apache-license-check
          apache-license-check --include-empty --copyright "Spotify AB"
